[package]
name = "real_engine"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true

[lib]
name = "real_engine"

[dependencies]
glfw.workspace = true
spdlog-rs.workspace = true
gl.workspace = true